# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b5de5fa182278912d9b3b669ae491d0ae56e2afac80c542a9ad7aa85adefdde12fd10c8ca0d8b44e71a1e6e59972c892899178bcb46bbfd1fa60d5ecba9136d

test:
  secret_key_base: 0cad648509144d873c3659b5ec4ac980ccfc68879888093169a85983a98829d4c42c8201a59d883da35f2902558b7d91cc133389d0a952af778f20520988b388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
